jdbc:
  driver: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/demo_01?characterEncoding=utf-8&serverTimezone=UTC
  username: root
  password: wedzbze74

# 激活配置文件需要其他配置文件的名塍
spring:
  profiles:
    active: abc,def
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo_01?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: wedzbze74
  redis:
    host: localhost
    port: 6379

# tomcat端口
server:
  port: 80

# 日志记录级别
logging:
  level:
    com.Jaziel: debug
    org.springframework: info

# mybatis 配置
mybatis:
  # 实体类别名包路径
  type-aliases-package: com.Jaziel.pojo
  # 映射文件路径
  # mapper-locations: classpath:mapper/*.xml
  configuration:
    # 控制台输出 sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
